telegrambot:
  user-name: "@YardSportsTeamLobbyBot"
  bot-token: 2023056122:AAHe9L2xN363Bvrch7RUOyw1byw5hR6I1g4
  webhook-path: https://f28c-34-253-143-52.ngrok.io

server:
  port: 5000

client:
  rest-api:
    base-url: "http://localhost:8080"

spring:
  mvc.hiddenmethod.filter.enabled: true
  messages:
    basename: i18n/messages
    fallback-to-system-locale: false

  redis:
    host: 192.168.99.100
    database: 0
    port: 6379

business:
  locale: ru